Pull Request for branch 'interactive' that contains functionality for deleting all completed items
jkanyi-web/ToDoList-App pull request #4
Opened 2023-03-31 14:09 UTC by jkanyi-web

- Added functionality for deleting all completed items

2023-03-31 14:22 UTC, frank1738 reviewed
Hi @jkanyi-web , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project with failing linter checks. Kindly fix them and resubmit your project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-31 15:06 UTC, jkanyi-web commented
Didn't you read my comment? It's not an issue with my code. Try cloning the
project and running all linter checks. Everything passes.

On Fri, 31 Mar 2023 at 17:22, Frankline Osoro ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Hi @jkanyi-web <https://github.com/jkanyi-web> ,
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> Invalid Code Review Request
>
>    - You have submitted a project with failing linter checks. Kindly fix
>    them and resubmit your project
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jkanyi-web/ToDoList-App/pull/4#pullrequestreview-1367043439>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXNG5CM7TR2VOHJAF2I46TW63SD5ANCNFSM6AAAAAAWOWS4ZE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-31 15:51 UTC, chrystalme commented
Hi @jkanyi-web, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that fails the linter test for web-hint. You can contact me on slack to talk more about the error.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-31 21:24 UTC, alexander16108 commented
Hi @jkanyi-web , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that fails the linter test for lighthouse

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-01 09:49 UTC, alexander16108 requested changes
Hi @jkanyi-web , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/2x0VePimPaFJDpGZ7H/giphy-downsized-medium.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 09:49 UTC, alexander16108 commented on src/index.js
> +removeCompleted();
as required your project should be able to store items in the local storage after reloading the page. but as I reload the page your items in the array saved in the local storage becomes empty please fix this and try again 👍🏾

2023-04-01 11:28 UTC, jkanyi-web commented
Items are already saved in local Storage though. In the requirements, I
haven't read anywhere that required the items to persist on page reload

On Sat, 1 Apr 2023 at 12:49, Alexander ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @jkanyi-web <https://github.com/jkanyi-web> ,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
>
> <https://camo.githubusercontent.com/05a65bf9c2d3070d088f4324ec62d5fdcb0132f4263d899d6979711d18bd45ce/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f327830566550696d5061464a4470475a37482f67697068792d646f776e73697a65642d6d656469756d2e676966>
> Highlights
>
> 📌 No Linters error ✅
> 📌 Descriptive pull request✅
> 📌 Good commit messages ✅
> 📌 Professional README file ✅
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In src/index.js
> <https://github.com/jkanyi-web/ToDoList-App/pull/4#discussion_r1155086315>
> :
>
> > +});
> +
> +removeCompleted();
>
> as required your project should be able to store items in the local
> storage after reloading the page. but as I reload the page your items in
> the array saved in the local storage becomes empty please fix this and try
> again 👍🏾
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jkanyi-web/ToDoList-App/pull/4#pullrequestreview-1367837698>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXNG5H3FYDA4X6PQYW2NSLW67235ANCNFSM6AAAAAAWOWS4ZE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-01 12:00 UTC, alexander16108 commented
@jkanyi-web 
![image](https://user-images.githubusercontent.com/60612329/229287365-cfedb231-7f02-4b56-a1b7-6116898ca7da.png)

2023-04-01 12:20 UTC, jkanyi-web commented
Oh thanks for that reminder Alexander, may I request for you to guide me
through this functionality, if you're available?

On Sat, 1 Apr 2023 at 15:00, Alexander ***@***.***> wrote:

> @jkanyi-web <https://github.com/jkanyi-web>
> [image: image]
> <https://user-images.githubusercontent.com/60612329/229287365-cfedb231-7f02-4b56-a1b7-6116898ca7da.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jkanyi-web/ToDoList-App/pull/4#issuecomment-1492950042>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXNG5HXS56K5ZRDF6VLEI3W7AKFZANCNFSM6AAAAAAWOWS4ZE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-01 14:55 UTC, cynthiainga approved these changes
Hi @jkanyi-web, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Correct GitHub flow ✔️ 
- [ ] Good design ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-03 09:50 UTC, merged